export const issue = {
  url: 'https://api.github.com/repos/atlassian/react-beautiful-dnd/issues/2482',
  repository_url: 'https://api.github.com/repos/atlassian/react-beautiful-dnd',
  labels_url:
    'https://api.github.com/repos/atlassian/react-beautiful-dnd/issues/2482/labels{/name}',
  comments_url:
    'https://api.github.com/repos/atlassian/react-beautiful-dnd/issues/2482/comments',
  events_url:
    'https://api.github.com/repos/atlassian/react-beautiful-dnd/issues/2482/events',
  html_url: 'https://github.com/atlassian/react-beautiful-dnd/pull/2482',
  id: 1610139522,
  node_id: 'PR_kwDOBfI-885LTV7z',
  number: 2482,
  title: 'Adding draggableId to DraggableLocation',
  user: {
    login: 'totaldict',
    id: 43420607,
    node_id: 'MDQ6VXNlcjQzNDIwNjA3',
    avatar_url: 'https://avatars.githubusercontent.com/u/43420607?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/totaldict',
    html_url: 'https://github.com/totaldict',
    followers_url: 'https://api.github.com/users/totaldict/followers',
    following_url:
      'https://api.github.com/users/totaldict/following{/other_user}',
    gists_url: 'https://api.github.com/users/totaldict/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/totaldict/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/totaldict/subscriptions',
    organizations_url: 'https://api.github.com/users/totaldict/orgs',
    repos_url: 'https://api.github.com/users/totaldict/repos',
    events_url: 'https://api.github.com/users/totaldict/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/totaldict/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [],
  state: 'open',
  locked: false,
  assignee: null,
  assignees: [],
  milestone: null,
  comments: 1,
  created_at: '2023-03-05T10:27:44Z',
  updated_at: '2023-04-23T13:28:07Z',
  closed_at: null,
  author_association: 'NONE',
  active_lock_reason: null,
  draft: false,
  pull_request: {
    url: 'https://api.github.com/repos/atlassian/react-beautiful-dnd/pulls/2482',
    html_url: 'https://github.com/atlassian/react-beautiful-dnd/pull/2482',
    diff_url: 'https://github.com/atlassian/react-beautiful-dnd/pull/2482.diff',
    patch_url:
      'https://github.com/atlassian/react-beautiful-dnd/pull/2482.patch',
    merged_at: null,
  },
  body: 'Adding ```draggableId``` to ```DraggableLocation``` (used in ```dragUpdate``` and ```dragEnd```, property - ```destination```).\r\n#2103 ',
  reactions: {
    url: 'https://api.github.com/repos/atlassian/react-beautiful-dnd/issues/2482/reactions',
    total_count: 0,
    '+1': 0,
    '-1': 0,
    laugh: 0,
    hooray: 0,
    confused: 0,
    heart: 0,
    rocket: 0,
    eyes: 0,
  },
  timeline_url:
    'https://api.github.com/repos/atlassian/react-beautiful-dnd/issues/2482/timeline',
  performed_via_github_app: null,
  state_reason: null,
}

export const profile = {
  id: 10270250,
  node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
  name: 'react',
  full_name: 'facebook/react',
  private: false,
  owner: {
    login: 'facebook',
    id: 69631,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
    avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/facebook',
    html_url: 'https://github.com/facebook',
    followers_url: 'https://api.github.com/users/facebook/followers',
    following_url:
      'https://api.github.com/users/facebook/following{/other_user}',
    gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
    organizations_url: 'https://api.github.com/users/facebook/orgs',
    repos_url: 'https://api.github.com/users/facebook/repos',
    events_url: 'https://api.github.com/users/facebook/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/facebook/received_events',
    type: 'Organization',
    site_admin: false,
  },
  html_url: 'https://github.com/facebook/react',
  description: 'The library for web and native user interfaces',
  fork: false,
  url: 'https://api.github.com/repos/facebook/react',
  forks_url: 'https://api.github.com/repos/facebook/react/forks',
  keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
  collaborators_url:
    'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/facebook/react/teams',
  hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
  issue_events_url:
    'https://api.github.com/repos/facebook/react/issues/events{/number}',
  events_url: 'https://api.github.com/repos/facebook/react/events',
  assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
  branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
  tags_url: 'https://api.github.com/repos/facebook/react/tags',
  blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/facebook/react/languages',
  stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
  contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
  subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
  subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
  commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
  git_commits_url:
    'https://api.github.com/repos/facebook/react/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
  issue_comment_url:
    'https://api.github.com/repos/facebook/react/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
  compare_url:
    'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/facebook/react/merges',
  archive_url:
    'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
  issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
  pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
  milestones_url:
    'https://api.github.com/repos/facebook/react/milestones{/number}',
  notifications_url:
    'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
  releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
  deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
  created_at: '2013-05-24T16:15:54Z',
  updated_at: '2023-05-14T19:02:56Z',
  pushed_at: '2023-05-14T16:38:29Z',
  git_url: 'git://github.com/facebook/react.git',
  ssh_url: 'git@github.com:facebook/react.git',
  clone_url: 'https://github.com/facebook/react.git',
  svn_url: 'https://github.com/facebook/react',
  homepage: 'https://react.dev',
  size: 321007,
  stargazers_count: 207368,
  watchers_count: 207368,
  language: 'JavaScript',
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: true,
  has_discussions: false,
  forks_count: 43261,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 1276,
  license: {
    key: 'mit',
    name: 'MIT License',
    spdx_id: 'MIT',
    url: 'https://api.github.com/licenses/mit',
    node_id: 'MDc6TGljZW5zZTEz',
  },
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: ['declarative', 'frontend', 'javascript', 'library', 'react', 'ui'],
  visibility: 'public',
  forks: 43261,
  open_issues: 1276,
  watchers: 207368,
  default_branch: 'main',
  temp_clone_token: null,
  organization: {
    login: 'facebook',
    id: 69631,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
    avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/facebook',
    html_url: 'https://github.com/facebook',
    followers_url: 'https://api.github.com/users/facebook/followers',
    following_url:
      'https://api.github.com/users/facebook/following{/other_user}',
    gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
    organizations_url: 'https://api.github.com/users/facebook/orgs',
    repos_url: 'https://api.github.com/users/facebook/repos',
    events_url: 'https://api.github.com/users/facebook/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/facebook/received_events',
    type: 'Organization',
    site_admin: false,
  },
  network_count: 43261,
  subscribers_count: 6632,
}
